# Generated by Django 2.1.2 on 2018-10-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('title_description', models.CharField(max_length=200, verbose_name='제목 설명')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_published', models.BooleanField(default=False, verbose_name='게시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
        ),
    ]
