# Generated by Django 2.1.2 on 2018-10-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(blank=True, default='', upload_to='main_image/'),
        ),
    ]
